server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: candidate-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/candidates/**

        - id: document-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/documents/**

        - id: chatbot-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/chatbot/**

        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/notify/**

        - id: task-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/tasks/**

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

